version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: buddy_postgres
    environment:
      POSTGRES_DB: buddy_db
      POSTGRES_USER: buddy_user
      POSTGRES_PASSWORD: buddy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buddy-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: buddy_backend
    environment:
      DB_USERNAME: buddy_user
      DB_PASSWORD: buddy_password
      JWT_SECRET: myVerySecretJWTKeyForBuddyApp2025
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - buddy-network
    volumes:
      - ./backend:/app
    command: ./mvnw spring-boot:run

volumes:
  postgres_data:

networks:
  buddy-network:
    driver: bridge 